// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PacketHead.proto

package com.dd.protobuf;

public final class CommonProtocol {
  private CommonProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PacketHeadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PacketHead)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string ActionId = 1;</code>
     */
    java.lang.String getActionId();
    /**
     * <code>string ActionId = 1;</code>
     */
    com.google.protobuf.ByteString
        getActionIdBytes();

    /**
     * <code>int32 ErrorCode = 2;</code>
     */
    int getErrorCode();

    /**
     * <code>string ErrorInfo = 3;</code>
     */
    java.lang.String getErrorInfo();
    /**
     * <code>string ErrorInfo = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrorInfoBytes();

    /**
     * <code>int32 Sid = 4;</code>
     */
    int getSid();

    /**
     * <code>string Uid = 5;</code>
     */
    java.lang.String getUid();
    /**
     * <code>string Uid = 5;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();
  }
  /**
   * Protobuf type {@code PacketHead}
   */
  public  static final class PacketHead extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PacketHead)
      PacketHeadOrBuilder {
    // Use PacketHead.newBuilder() to construct.
    private PacketHead(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PacketHead() {
      actionId_ = "";
      errorCode_ = 0;
      errorInfo_ = "";
      sid_ = 0;
      uid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PacketHead(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              actionId_ = s;
              break;
            }
            case 16: {

              errorCode_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              errorInfo_ = s;
              break;
            }
            case 32: {

              sid_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              uid_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dd.protobuf.CommonProtocol.internal_static_PacketHead_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dd.protobuf.CommonProtocol.internal_static_PacketHead_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dd.protobuf.CommonProtocol.PacketHead.class, com.dd.protobuf.CommonProtocol.PacketHead.Builder.class);
    }

    public static final int ACTIONID_FIELD_NUMBER = 1;
    private volatile java.lang.Object actionId_;
    /**
     * <code>string ActionId = 1;</code>
     */
    public java.lang.String getActionId() {
      java.lang.Object ref = actionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actionId_ = s;
        return s;
      }
    }
    /**
     * <code>string ActionId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getActionIdBytes() {
      java.lang.Object ref = actionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORCODE_FIELD_NUMBER = 2;
    private int errorCode_;
    /**
     * <code>int32 ErrorCode = 2;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    public static final int ERRORINFO_FIELD_NUMBER = 3;
    private volatile java.lang.Object errorInfo_;
    /**
     * <code>string ErrorInfo = 3;</code>
     */
    public java.lang.String getErrorInfo() {
      java.lang.Object ref = errorInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorInfo_ = s;
        return s;
      }
    }
    /**
     * <code>string ErrorInfo = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrorInfoBytes() {
      java.lang.Object ref = errorInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SID_FIELD_NUMBER = 4;
    private int sid_;
    /**
     * <code>int32 Sid = 4;</code>
     */
    public int getSid() {
      return sid_;
    }

    public static final int UID_FIELD_NUMBER = 5;
    private volatile java.lang.Object uid_;
    /**
     * <code>string Uid = 5;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <code>string Uid = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getActionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, actionId_);
      }
      if (errorCode_ != 0) {
        output.writeInt32(2, errorCode_);
      }
      if (!getErrorInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errorInfo_);
      }
      if (sid_ != 0) {
        output.writeInt32(4, sid_);
      }
      if (!getUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, uid_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getActionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, actionId_);
      }
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, errorCode_);
      }
      if (!getErrorInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errorInfo_);
      }
      if (sid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, sid_);
      }
      if (!getUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, uid_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dd.protobuf.CommonProtocol.PacketHead)) {
        return super.equals(obj);
      }
      com.dd.protobuf.CommonProtocol.PacketHead other = (com.dd.protobuf.CommonProtocol.PacketHead) obj;

      boolean result = true;
      result = result && getActionId()
          .equals(other.getActionId());
      result = result && (getErrorCode()
          == other.getErrorCode());
      result = result && getErrorInfo()
          .equals(other.getErrorInfo());
      result = result && (getSid()
          == other.getSid());
      result = result && getUid()
          .equals(other.getUid());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACTIONID_FIELD_NUMBER;
      hash = (53 * hash) + getActionId().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      hash = (37 * hash) + ERRORINFO_FIELD_NUMBER;
      hash = (53 * hash) + getErrorInfo().hashCode();
      hash = (37 * hash) + SID_FIELD_NUMBER;
      hash = (53 * hash) + getSid();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dd.protobuf.CommonProtocol.PacketHead parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dd.protobuf.CommonProtocol.PacketHead parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dd.protobuf.CommonProtocol.PacketHead parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dd.protobuf.CommonProtocol.PacketHead parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dd.protobuf.CommonProtocol.PacketHead parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.CommonProtocol.PacketHead parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dd.protobuf.CommonProtocol.PacketHead parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.CommonProtocol.PacketHead parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dd.protobuf.CommonProtocol.PacketHead parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.CommonProtocol.PacketHead parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dd.protobuf.CommonProtocol.PacketHead prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PacketHead}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PacketHead)
        com.dd.protobuf.CommonProtocol.PacketHeadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dd.protobuf.CommonProtocol.internal_static_PacketHead_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dd.protobuf.CommonProtocol.internal_static_PacketHead_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dd.protobuf.CommonProtocol.PacketHead.class, com.dd.protobuf.CommonProtocol.PacketHead.Builder.class);
      }

      // Construct using com.dd.protobuf.CommonProtocol.PacketHead.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        actionId_ = "";

        errorCode_ = 0;

        errorInfo_ = "";

        sid_ = 0;

        uid_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dd.protobuf.CommonProtocol.internal_static_PacketHead_descriptor;
      }

      public com.dd.protobuf.CommonProtocol.PacketHead getDefaultInstanceForType() {
        return com.dd.protobuf.CommonProtocol.PacketHead.getDefaultInstance();
      }

      public com.dd.protobuf.CommonProtocol.PacketHead build() {
        com.dd.protobuf.CommonProtocol.PacketHead result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dd.protobuf.CommonProtocol.PacketHead buildPartial() {
        com.dd.protobuf.CommonProtocol.PacketHead result = new com.dd.protobuf.CommonProtocol.PacketHead(this);
        result.actionId_ = actionId_;
        result.errorCode_ = errorCode_;
        result.errorInfo_ = errorInfo_;
        result.sid_ = sid_;
        result.uid_ = uid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dd.protobuf.CommonProtocol.PacketHead) {
          return mergeFrom((com.dd.protobuf.CommonProtocol.PacketHead)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dd.protobuf.CommonProtocol.PacketHead other) {
        if (other == com.dd.protobuf.CommonProtocol.PacketHead.getDefaultInstance()) return this;
        if (!other.getActionId().isEmpty()) {
          actionId_ = other.actionId_;
          onChanged();
        }
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        if (!other.getErrorInfo().isEmpty()) {
          errorInfo_ = other.errorInfo_;
          onChanged();
        }
        if (other.getSid() != 0) {
          setSid(other.getSid());
        }
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dd.protobuf.CommonProtocol.PacketHead parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dd.protobuf.CommonProtocol.PacketHead) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object actionId_ = "";
      /**
       * <code>string ActionId = 1;</code>
       */
      public java.lang.String getActionId() {
        java.lang.Object ref = actionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          actionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ActionId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getActionIdBytes() {
        java.lang.Object ref = actionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          actionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ActionId = 1;</code>
       */
      public Builder setActionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        actionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ActionId = 1;</code>
       */
      public Builder clearActionId() {
        
        actionId_ = getDefaultInstance().getActionId();
        onChanged();
        return this;
      }
      /**
       * <code>string ActionId = 1;</code>
       */
      public Builder setActionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        actionId_ = value;
        onChanged();
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>int32 ErrorCode = 2;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>int32 ErrorCode = 2;</code>
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ErrorCode = 2;</code>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errorInfo_ = "";
      /**
       * <code>string ErrorInfo = 3;</code>
       */
      public java.lang.String getErrorInfo() {
        java.lang.Object ref = errorInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errorInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ErrorInfo = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrorInfoBytes() {
        java.lang.Object ref = errorInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ErrorInfo = 3;</code>
       */
      public Builder setErrorInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ErrorInfo = 3;</code>
       */
      public Builder clearErrorInfo() {
        
        errorInfo_ = getDefaultInstance().getErrorInfo();
        onChanged();
        return this;
      }
      /**
       * <code>string ErrorInfo = 3;</code>
       */
      public Builder setErrorInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorInfo_ = value;
        onChanged();
        return this;
      }

      private int sid_ ;
      /**
       * <code>int32 Sid = 4;</code>
       */
      public int getSid() {
        return sid_;
      }
      /**
       * <code>int32 Sid = 4;</code>
       */
      public Builder setSid(int value) {
        
        sid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Sid = 4;</code>
       */
      public Builder clearSid() {
        
        sid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object uid_ = "";
      /**
       * <code>string Uid = 5;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Uid = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Uid = 5;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Uid = 5;</code>
       */
      public Builder clearUid() {
        
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>string Uid = 5;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uid_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PacketHead)
    }

    // @@protoc_insertion_point(class_scope:PacketHead)
    private static final com.dd.protobuf.CommonProtocol.PacketHead DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dd.protobuf.CommonProtocol.PacketHead();
    }

    public static com.dd.protobuf.CommonProtocol.PacketHead getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PacketHead>
        PARSER = new com.google.protobuf.AbstractParser<PacketHead>() {
      public PacketHead parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PacketHead(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PacketHead> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PacketHead> getParserForType() {
      return PARSER;
    }

    public com.dd.protobuf.CommonProtocol.PacketHead getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PacketHead_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PacketHead_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020PacketHead.proto\"^\n\nPacketHead\022\020\n\010Acti" +
      "onId\030\001 \001(\t\022\021\n\tErrorCode\030\002 \001(\005\022\021\n\tErrorIn" +
      "fo\030\003 \001(\t\022\013\n\003Sid\030\004 \001(\005\022\013\n\003Uid\030\005 \001(\tB!\n\017co" +
      "m.dd.protobufB\016CommonProtocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PacketHead_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PacketHead_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PacketHead_descriptor,
        new java.lang.String[] { "ActionId", "ErrorCode", "ErrorInfo", "Sid", "Uid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
