// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gate.proto

package com.dd.protobuf;

public final class GateProtocol {
  private GateProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CSInnerServerRegisterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CSInnerServerRegister)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *服务器ID
     * </pre>
     *
     * <code>int32 sid = 1;</code>
     */
    int getSid();

    /**
     * <code>int32 type = 2;</code>
     */
    int getType();

    /**
     * <code>string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code CSInnerServerRegister}
   */
  public  static final class CSInnerServerRegister extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CSInnerServerRegister)
      CSInnerServerRegisterOrBuilder {
    // Use CSInnerServerRegister.newBuilder() to construct.
    private CSInnerServerRegister(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CSInnerServerRegister() {
      sid_ = 0;
      type_ = 0;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CSInnerServerRegister(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              sid_ = input.readInt32();
              break;
            }
            case 16: {

              type_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dd.protobuf.GateProtocol.internal_static_CSInnerServerRegister_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dd.protobuf.GateProtocol.internal_static_CSInnerServerRegister_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dd.protobuf.GateProtocol.CSInnerServerRegister.class, com.dd.protobuf.GateProtocol.CSInnerServerRegister.Builder.class);
    }

    public static final int SID_FIELD_NUMBER = 1;
    private int sid_;
    /**
     * <pre>
     *服务器ID
     * </pre>
     *
     * <code>int32 sid = 1;</code>
     */
    public int getSid() {
      return sid_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>int32 type = 2;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sid_ != 0) {
        output.writeInt32(1, sid_);
      }
      if (type_ != 0) {
        output.writeInt32(2, type_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sid_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dd.protobuf.GateProtocol.CSInnerServerRegister)) {
        return super.equals(obj);
      }
      com.dd.protobuf.GateProtocol.CSInnerServerRegister other = (com.dd.protobuf.GateProtocol.CSInnerServerRegister) obj;

      boolean result = true;
      result = result && (getSid()
          == other.getSid());
      result = result && (getType()
          == other.getType());
      result = result && getName()
          .equals(other.getName());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SID_FIELD_NUMBER;
      hash = (53 * hash) + getSid();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dd.protobuf.GateProtocol.CSInnerServerRegister parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dd.protobuf.GateProtocol.CSInnerServerRegister parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dd.protobuf.GateProtocol.CSInnerServerRegister parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dd.protobuf.GateProtocol.CSInnerServerRegister parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dd.protobuf.GateProtocol.CSInnerServerRegister parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.GateProtocol.CSInnerServerRegister parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dd.protobuf.GateProtocol.CSInnerServerRegister parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.GateProtocol.CSInnerServerRegister parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dd.protobuf.GateProtocol.CSInnerServerRegister parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.GateProtocol.CSInnerServerRegister parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dd.protobuf.GateProtocol.CSInnerServerRegister prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CSInnerServerRegister}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CSInnerServerRegister)
        com.dd.protobuf.GateProtocol.CSInnerServerRegisterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dd.protobuf.GateProtocol.internal_static_CSInnerServerRegister_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dd.protobuf.GateProtocol.internal_static_CSInnerServerRegister_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dd.protobuf.GateProtocol.CSInnerServerRegister.class, com.dd.protobuf.GateProtocol.CSInnerServerRegister.Builder.class);
      }

      // Construct using com.dd.protobuf.GateProtocol.CSInnerServerRegister.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sid_ = 0;

        type_ = 0;

        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dd.protobuf.GateProtocol.internal_static_CSInnerServerRegister_descriptor;
      }

      public com.dd.protobuf.GateProtocol.CSInnerServerRegister getDefaultInstanceForType() {
        return com.dd.protobuf.GateProtocol.CSInnerServerRegister.getDefaultInstance();
      }

      public com.dd.protobuf.GateProtocol.CSInnerServerRegister build() {
        com.dd.protobuf.GateProtocol.CSInnerServerRegister result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dd.protobuf.GateProtocol.CSInnerServerRegister buildPartial() {
        com.dd.protobuf.GateProtocol.CSInnerServerRegister result = new com.dd.protobuf.GateProtocol.CSInnerServerRegister(this);
        result.sid_ = sid_;
        result.type_ = type_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dd.protobuf.GateProtocol.CSInnerServerRegister) {
          return mergeFrom((com.dd.protobuf.GateProtocol.CSInnerServerRegister)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dd.protobuf.GateProtocol.CSInnerServerRegister other) {
        if (other == com.dd.protobuf.GateProtocol.CSInnerServerRegister.getDefaultInstance()) return this;
        if (other.getSid() != 0) {
          setSid(other.getSid());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dd.protobuf.GateProtocol.CSInnerServerRegister parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dd.protobuf.GateProtocol.CSInnerServerRegister) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int sid_ ;
      /**
       * <pre>
       *服务器ID
       * </pre>
       *
       * <code>int32 sid = 1;</code>
       */
      public int getSid() {
        return sid_;
      }
      /**
       * <pre>
       *服务器ID
       * </pre>
       *
       * <code>int32 sid = 1;</code>
       */
      public Builder setSid(int value) {
        
        sid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务器ID
       * </pre>
       *
       * <code>int32 sid = 1;</code>
       */
      public Builder clearSid() {
        
        sid_ = 0;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 2;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 2;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:CSInnerServerRegister)
    }

    // @@protoc_insertion_point(class_scope:CSInnerServerRegister)
    private static final com.dd.protobuf.GateProtocol.CSInnerServerRegister DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dd.protobuf.GateProtocol.CSInnerServerRegister();
    }

    public static com.dd.protobuf.GateProtocol.CSInnerServerRegister getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CSInnerServerRegister>
        PARSER = new com.google.protobuf.AbstractParser<CSInnerServerRegister>() {
      public CSInnerServerRegister parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CSInnerServerRegister(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CSInnerServerRegister> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CSInnerServerRegister> getParserForType() {
      return PARSER;
    }

    public com.dd.protobuf.GateProtocol.CSInnerServerRegister getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SCInnerServerRegisterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SCInnerServerRegister)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 sid = 1;</code>
     */
    int getSid();

    /**
     * <code>string udpIp = 2;</code>
     */
    java.lang.String getUdpIp();
    /**
     * <code>string udpIp = 2;</code>
     */
    com.google.protobuf.ByteString
        getUdpIpBytes();

    /**
     * <code>int32 udpPort = 3;</code>
     */
    int getUdpPort();
  }
  /**
   * Protobuf type {@code SCInnerServerRegister}
   */
  public  static final class SCInnerServerRegister extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SCInnerServerRegister)
      SCInnerServerRegisterOrBuilder {
    // Use SCInnerServerRegister.newBuilder() to construct.
    private SCInnerServerRegister(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SCInnerServerRegister() {
      sid_ = 0;
      udpIp_ = "";
      udpPort_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SCInnerServerRegister(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              sid_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              udpIp_ = s;
              break;
            }
            case 24: {

              udpPort_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dd.protobuf.GateProtocol.internal_static_SCInnerServerRegister_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dd.protobuf.GateProtocol.internal_static_SCInnerServerRegister_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dd.protobuf.GateProtocol.SCInnerServerRegister.class, com.dd.protobuf.GateProtocol.SCInnerServerRegister.Builder.class);
    }

    public static final int SID_FIELD_NUMBER = 1;
    private int sid_;
    /**
     * <code>int32 sid = 1;</code>
     */
    public int getSid() {
      return sid_;
    }

    public static final int UDPIP_FIELD_NUMBER = 2;
    private volatile java.lang.Object udpIp_;
    /**
     * <code>string udpIp = 2;</code>
     */
    public java.lang.String getUdpIp() {
      java.lang.Object ref = udpIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        udpIp_ = s;
        return s;
      }
    }
    /**
     * <code>string udpIp = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUdpIpBytes() {
      java.lang.Object ref = udpIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        udpIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UDPPORT_FIELD_NUMBER = 3;
    private int udpPort_;
    /**
     * <code>int32 udpPort = 3;</code>
     */
    public int getUdpPort() {
      return udpPort_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sid_ != 0) {
        output.writeInt32(1, sid_);
      }
      if (!getUdpIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, udpIp_);
      }
      if (udpPort_ != 0) {
        output.writeInt32(3, udpPort_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sid_);
      }
      if (!getUdpIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, udpIp_);
      }
      if (udpPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, udpPort_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dd.protobuf.GateProtocol.SCInnerServerRegister)) {
        return super.equals(obj);
      }
      com.dd.protobuf.GateProtocol.SCInnerServerRegister other = (com.dd.protobuf.GateProtocol.SCInnerServerRegister) obj;

      boolean result = true;
      result = result && (getSid()
          == other.getSid());
      result = result && getUdpIp()
          .equals(other.getUdpIp());
      result = result && (getUdpPort()
          == other.getUdpPort());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SID_FIELD_NUMBER;
      hash = (53 * hash) + getSid();
      hash = (37 * hash) + UDPIP_FIELD_NUMBER;
      hash = (53 * hash) + getUdpIp().hashCode();
      hash = (37 * hash) + UDPPORT_FIELD_NUMBER;
      hash = (53 * hash) + getUdpPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dd.protobuf.GateProtocol.SCInnerServerRegister parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dd.protobuf.GateProtocol.SCInnerServerRegister parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dd.protobuf.GateProtocol.SCInnerServerRegister parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dd.protobuf.GateProtocol.SCInnerServerRegister parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dd.protobuf.GateProtocol.SCInnerServerRegister parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.GateProtocol.SCInnerServerRegister parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dd.protobuf.GateProtocol.SCInnerServerRegister parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.GateProtocol.SCInnerServerRegister parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dd.protobuf.GateProtocol.SCInnerServerRegister parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.GateProtocol.SCInnerServerRegister parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dd.protobuf.GateProtocol.SCInnerServerRegister prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SCInnerServerRegister}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SCInnerServerRegister)
        com.dd.protobuf.GateProtocol.SCInnerServerRegisterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dd.protobuf.GateProtocol.internal_static_SCInnerServerRegister_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dd.protobuf.GateProtocol.internal_static_SCInnerServerRegister_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dd.protobuf.GateProtocol.SCInnerServerRegister.class, com.dd.protobuf.GateProtocol.SCInnerServerRegister.Builder.class);
      }

      // Construct using com.dd.protobuf.GateProtocol.SCInnerServerRegister.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sid_ = 0;

        udpIp_ = "";

        udpPort_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dd.protobuf.GateProtocol.internal_static_SCInnerServerRegister_descriptor;
      }

      public com.dd.protobuf.GateProtocol.SCInnerServerRegister getDefaultInstanceForType() {
        return com.dd.protobuf.GateProtocol.SCInnerServerRegister.getDefaultInstance();
      }

      public com.dd.protobuf.GateProtocol.SCInnerServerRegister build() {
        com.dd.protobuf.GateProtocol.SCInnerServerRegister result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dd.protobuf.GateProtocol.SCInnerServerRegister buildPartial() {
        com.dd.protobuf.GateProtocol.SCInnerServerRegister result = new com.dd.protobuf.GateProtocol.SCInnerServerRegister(this);
        result.sid_ = sid_;
        result.udpIp_ = udpIp_;
        result.udpPort_ = udpPort_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dd.protobuf.GateProtocol.SCInnerServerRegister) {
          return mergeFrom((com.dd.protobuf.GateProtocol.SCInnerServerRegister)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dd.protobuf.GateProtocol.SCInnerServerRegister other) {
        if (other == com.dd.protobuf.GateProtocol.SCInnerServerRegister.getDefaultInstance()) return this;
        if (other.getSid() != 0) {
          setSid(other.getSid());
        }
        if (!other.getUdpIp().isEmpty()) {
          udpIp_ = other.udpIp_;
          onChanged();
        }
        if (other.getUdpPort() != 0) {
          setUdpPort(other.getUdpPort());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dd.protobuf.GateProtocol.SCInnerServerRegister parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dd.protobuf.GateProtocol.SCInnerServerRegister) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int sid_ ;
      /**
       * <code>int32 sid = 1;</code>
       */
      public int getSid() {
        return sid_;
      }
      /**
       * <code>int32 sid = 1;</code>
       */
      public Builder setSid(int value) {
        
        sid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sid = 1;</code>
       */
      public Builder clearSid() {
        
        sid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object udpIp_ = "";
      /**
       * <code>string udpIp = 2;</code>
       */
      public java.lang.String getUdpIp() {
        java.lang.Object ref = udpIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          udpIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string udpIp = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUdpIpBytes() {
        java.lang.Object ref = udpIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          udpIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string udpIp = 2;</code>
       */
      public Builder setUdpIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        udpIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string udpIp = 2;</code>
       */
      public Builder clearUdpIp() {
        
        udpIp_ = getDefaultInstance().getUdpIp();
        onChanged();
        return this;
      }
      /**
       * <code>string udpIp = 2;</code>
       */
      public Builder setUdpIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        udpIp_ = value;
        onChanged();
        return this;
      }

      private int udpPort_ ;
      /**
       * <code>int32 udpPort = 3;</code>
       */
      public int getUdpPort() {
        return udpPort_;
      }
      /**
       * <code>int32 udpPort = 3;</code>
       */
      public Builder setUdpPort(int value) {
        
        udpPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 udpPort = 3;</code>
       */
      public Builder clearUdpPort() {
        
        udpPort_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SCInnerServerRegister)
    }

    // @@protoc_insertion_point(class_scope:SCInnerServerRegister)
    private static final com.dd.protobuf.GateProtocol.SCInnerServerRegister DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dd.protobuf.GateProtocol.SCInnerServerRegister();
    }

    public static com.dd.protobuf.GateProtocol.SCInnerServerRegister getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SCInnerServerRegister>
        PARSER = new com.google.protobuf.AbstractParser<SCInnerServerRegister>() {
      public SCInnerServerRegister parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SCInnerServerRegister(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SCInnerServerRegister> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SCInnerServerRegister> getParserForType() {
      return PARSER;
    }

    public com.dd.protobuf.GateProtocol.SCInnerServerRegister getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CSInnerServerRegister_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CSInnerServerRegister_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SCInnerServerRegister_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SCInnerServerRegister_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nGate.proto\"@\n\025CSInnerServerRegister\022\013\n" +
      "\003sid\030\001 \001(\005\022\014\n\004type\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\"D" +
      "\n\025SCInnerServerRegister\022\013\n\003sid\030\001 \001(\005\022\r\n\005" +
      "udpIp\030\002 \001(\t\022\017\n\007udpPort\030\003 \001(\005B\037\n\017com.dd.p" +
      "rotobufB\014GateProtocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CSInnerServerRegister_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CSInnerServerRegister_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CSInnerServerRegister_descriptor,
        new java.lang.String[] { "Sid", "Type", "Name", });
    internal_static_SCInnerServerRegister_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SCInnerServerRegister_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SCInnerServerRegister_descriptor,
        new java.lang.String[] { "Sid", "UdpIp", "UdpPort", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
