// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeartBeat.proto

package com.dd.protobuf;

public final class HeartBeatProtocol {
  private HeartBeatProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CSHeartBeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CSHeartBeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string ClientTime = 1;</code>
     */
    java.lang.String getClientTime();
    /**
     * <code>string ClientTime = 1;</code>
     */
    com.google.protobuf.ByteString
        getClientTimeBytes();
  }
  /**
   * Protobuf type {@code CSHeartBeat}
   */
  public  static final class CSHeartBeat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CSHeartBeat)
      CSHeartBeatOrBuilder {
    // Use CSHeartBeat.newBuilder() to construct.
    private CSHeartBeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CSHeartBeat() {
      clientTime_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CSHeartBeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              clientTime_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dd.protobuf.HeartBeatProtocol.internal_static_CSHeartBeat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dd.protobuf.HeartBeatProtocol.internal_static_CSHeartBeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dd.protobuf.HeartBeatProtocol.CSHeartBeat.class, com.dd.protobuf.HeartBeatProtocol.CSHeartBeat.Builder.class);
    }

    public static final int CLIENTTIME_FIELD_NUMBER = 1;
    private volatile java.lang.Object clientTime_;
    /**
     * <code>string ClientTime = 1;</code>
     */
    public java.lang.String getClientTime() {
      java.lang.Object ref = clientTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientTime_ = s;
        return s;
      }
    }
    /**
     * <code>string ClientTime = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientTimeBytes() {
      java.lang.Object ref = clientTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClientTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientTime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClientTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientTime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dd.protobuf.HeartBeatProtocol.CSHeartBeat)) {
        return super.equals(obj);
      }
      com.dd.protobuf.HeartBeatProtocol.CSHeartBeat other = (com.dd.protobuf.HeartBeatProtocol.CSHeartBeat) obj;

      boolean result = true;
      result = result && getClientTime()
          .equals(other.getClientTime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENTTIME_FIELD_NUMBER;
      hash = (53 * hash) + getClientTime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dd.protobuf.HeartBeatProtocol.CSHeartBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dd.protobuf.HeartBeatProtocol.CSHeartBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dd.protobuf.HeartBeatProtocol.CSHeartBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dd.protobuf.HeartBeatProtocol.CSHeartBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dd.protobuf.HeartBeatProtocol.CSHeartBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.HeartBeatProtocol.CSHeartBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dd.protobuf.HeartBeatProtocol.CSHeartBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.HeartBeatProtocol.CSHeartBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dd.protobuf.HeartBeatProtocol.CSHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.HeartBeatProtocol.CSHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dd.protobuf.HeartBeatProtocol.CSHeartBeat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CSHeartBeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CSHeartBeat)
        com.dd.protobuf.HeartBeatProtocol.CSHeartBeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dd.protobuf.HeartBeatProtocol.internal_static_CSHeartBeat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dd.protobuf.HeartBeatProtocol.internal_static_CSHeartBeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dd.protobuf.HeartBeatProtocol.CSHeartBeat.class, com.dd.protobuf.HeartBeatProtocol.CSHeartBeat.Builder.class);
      }

      // Construct using com.dd.protobuf.HeartBeatProtocol.CSHeartBeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        clientTime_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dd.protobuf.HeartBeatProtocol.internal_static_CSHeartBeat_descriptor;
      }

      public com.dd.protobuf.HeartBeatProtocol.CSHeartBeat getDefaultInstanceForType() {
        return com.dd.protobuf.HeartBeatProtocol.CSHeartBeat.getDefaultInstance();
      }

      public com.dd.protobuf.HeartBeatProtocol.CSHeartBeat build() {
        com.dd.protobuf.HeartBeatProtocol.CSHeartBeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dd.protobuf.HeartBeatProtocol.CSHeartBeat buildPartial() {
        com.dd.protobuf.HeartBeatProtocol.CSHeartBeat result = new com.dd.protobuf.HeartBeatProtocol.CSHeartBeat(this);
        result.clientTime_ = clientTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dd.protobuf.HeartBeatProtocol.CSHeartBeat) {
          return mergeFrom((com.dd.protobuf.HeartBeatProtocol.CSHeartBeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dd.protobuf.HeartBeatProtocol.CSHeartBeat other) {
        if (other == com.dd.protobuf.HeartBeatProtocol.CSHeartBeat.getDefaultInstance()) return this;
        if (!other.getClientTime().isEmpty()) {
          clientTime_ = other.clientTime_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dd.protobuf.HeartBeatProtocol.CSHeartBeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dd.protobuf.HeartBeatProtocol.CSHeartBeat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object clientTime_ = "";
      /**
       * <code>string ClientTime = 1;</code>
       */
      public java.lang.String getClientTime() {
        java.lang.Object ref = clientTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ClientTime = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClientTimeBytes() {
        java.lang.Object ref = clientTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ClientTime = 1;</code>
       */
      public Builder setClientTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ClientTime = 1;</code>
       */
      public Builder clearClientTime() {
        
        clientTime_ = getDefaultInstance().getClientTime();
        onChanged();
        return this;
      }
      /**
       * <code>string ClientTime = 1;</code>
       */
      public Builder setClientTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientTime_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:CSHeartBeat)
    }

    // @@protoc_insertion_point(class_scope:CSHeartBeat)
    private static final com.dd.protobuf.HeartBeatProtocol.CSHeartBeat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dd.protobuf.HeartBeatProtocol.CSHeartBeat();
    }

    public static com.dd.protobuf.HeartBeatProtocol.CSHeartBeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CSHeartBeat>
        PARSER = new com.google.protobuf.AbstractParser<CSHeartBeat>() {
      public CSHeartBeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CSHeartBeat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CSHeartBeat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CSHeartBeat> getParserForType() {
      return PARSER;
    }

    public com.dd.protobuf.HeartBeatProtocol.CSHeartBeat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SCHeartBeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SCHeartBeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string ServerTime = 1;</code>
     */
    java.lang.String getServerTime();
    /**
     * <code>string ServerTime = 1;</code>
     */
    com.google.protobuf.ByteString
        getServerTimeBytes();
  }
  /**
   * Protobuf type {@code SCHeartBeat}
   */
  public  static final class SCHeartBeat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SCHeartBeat)
      SCHeartBeatOrBuilder {
    // Use SCHeartBeat.newBuilder() to construct.
    private SCHeartBeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SCHeartBeat() {
      serverTime_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SCHeartBeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              serverTime_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dd.protobuf.HeartBeatProtocol.internal_static_SCHeartBeat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dd.protobuf.HeartBeatProtocol.internal_static_SCHeartBeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dd.protobuf.HeartBeatProtocol.SCHeartBeat.class, com.dd.protobuf.HeartBeatProtocol.SCHeartBeat.Builder.class);
    }

    public static final int SERVERTIME_FIELD_NUMBER = 1;
    private volatile java.lang.Object serverTime_;
    /**
     * <code>string ServerTime = 1;</code>
     */
    public java.lang.String getServerTime() {
      java.lang.Object ref = serverTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverTime_ = s;
        return s;
      }
    }
    /**
     * <code>string ServerTime = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServerTimeBytes() {
      java.lang.Object ref = serverTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getServerTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serverTime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getServerTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serverTime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dd.protobuf.HeartBeatProtocol.SCHeartBeat)) {
        return super.equals(obj);
      }
      com.dd.protobuf.HeartBeatProtocol.SCHeartBeat other = (com.dd.protobuf.HeartBeatProtocol.SCHeartBeat) obj;

      boolean result = true;
      result = result && getServerTime()
          .equals(other.getServerTime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVERTIME_FIELD_NUMBER;
      hash = (53 * hash) + getServerTime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dd.protobuf.HeartBeatProtocol.SCHeartBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dd.protobuf.HeartBeatProtocol.SCHeartBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dd.protobuf.HeartBeatProtocol.SCHeartBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dd.protobuf.HeartBeatProtocol.SCHeartBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dd.protobuf.HeartBeatProtocol.SCHeartBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.HeartBeatProtocol.SCHeartBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dd.protobuf.HeartBeatProtocol.SCHeartBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.HeartBeatProtocol.SCHeartBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dd.protobuf.HeartBeatProtocol.SCHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.HeartBeatProtocol.SCHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dd.protobuf.HeartBeatProtocol.SCHeartBeat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SCHeartBeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SCHeartBeat)
        com.dd.protobuf.HeartBeatProtocol.SCHeartBeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dd.protobuf.HeartBeatProtocol.internal_static_SCHeartBeat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dd.protobuf.HeartBeatProtocol.internal_static_SCHeartBeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dd.protobuf.HeartBeatProtocol.SCHeartBeat.class, com.dd.protobuf.HeartBeatProtocol.SCHeartBeat.Builder.class);
      }

      // Construct using com.dd.protobuf.HeartBeatProtocol.SCHeartBeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serverTime_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dd.protobuf.HeartBeatProtocol.internal_static_SCHeartBeat_descriptor;
      }

      public com.dd.protobuf.HeartBeatProtocol.SCHeartBeat getDefaultInstanceForType() {
        return com.dd.protobuf.HeartBeatProtocol.SCHeartBeat.getDefaultInstance();
      }

      public com.dd.protobuf.HeartBeatProtocol.SCHeartBeat build() {
        com.dd.protobuf.HeartBeatProtocol.SCHeartBeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dd.protobuf.HeartBeatProtocol.SCHeartBeat buildPartial() {
        com.dd.protobuf.HeartBeatProtocol.SCHeartBeat result = new com.dd.protobuf.HeartBeatProtocol.SCHeartBeat(this);
        result.serverTime_ = serverTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dd.protobuf.HeartBeatProtocol.SCHeartBeat) {
          return mergeFrom((com.dd.protobuf.HeartBeatProtocol.SCHeartBeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dd.protobuf.HeartBeatProtocol.SCHeartBeat other) {
        if (other == com.dd.protobuf.HeartBeatProtocol.SCHeartBeat.getDefaultInstance()) return this;
        if (!other.getServerTime().isEmpty()) {
          serverTime_ = other.serverTime_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dd.protobuf.HeartBeatProtocol.SCHeartBeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dd.protobuf.HeartBeatProtocol.SCHeartBeat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object serverTime_ = "";
      /**
       * <code>string ServerTime = 1;</code>
       */
      public java.lang.String getServerTime() {
        java.lang.Object ref = serverTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serverTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ServerTime = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServerTimeBytes() {
        java.lang.Object ref = serverTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ServerTime = 1;</code>
       */
      public Builder setServerTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ServerTime = 1;</code>
       */
      public Builder clearServerTime() {
        
        serverTime_ = getDefaultInstance().getServerTime();
        onChanged();
        return this;
      }
      /**
       * <code>string ServerTime = 1;</code>
       */
      public Builder setServerTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverTime_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SCHeartBeat)
    }

    // @@protoc_insertion_point(class_scope:SCHeartBeat)
    private static final com.dd.protobuf.HeartBeatProtocol.SCHeartBeat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dd.protobuf.HeartBeatProtocol.SCHeartBeat();
    }

    public static com.dd.protobuf.HeartBeatProtocol.SCHeartBeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SCHeartBeat>
        PARSER = new com.google.protobuf.AbstractParser<SCHeartBeat>() {
      public SCHeartBeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SCHeartBeat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SCHeartBeat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SCHeartBeat> getParserForType() {
      return PARSER;
    }

    public com.dd.protobuf.HeartBeatProtocol.SCHeartBeat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CSHeartBeat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CSHeartBeat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SCHeartBeat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SCHeartBeat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017HeartBeat.proto\"!\n\013CSHeartBeat\022\022\n\nClie" +
      "ntTime\030\001 \001(\t\"!\n\013SCHeartBeat\022\022\n\nServerTim" +
      "e\030\001 \001(\tB$\n\017com.dd.protobufB\021HeartBeatPro" +
      "tocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CSHeartBeat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CSHeartBeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CSHeartBeat_descriptor,
        new java.lang.String[] { "ClientTime", });
    internal_static_SCHeartBeat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SCHeartBeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SCHeartBeat_descriptor,
        new java.lang.String[] { "ServerTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
