// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

package com.dd.protobuf;

public final class LoginProtocol {
  private LoginProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CSLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CSLogin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string DeviceId = 1;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <code>string DeviceId = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>string UserId = 2;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>string UserId = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string zoneName = 3;</code>
     */
    java.lang.String getZoneName();
    /**
     * <code>string zoneName = 3;</code>
     */
    com.google.protobuf.ByteString
        getZoneNameBytes();

    /**
     * <code>string account = 4;</code>
     */
    java.lang.String getAccount();
    /**
     * <code>string account = 4;</code>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <code>string gaid = 5;</code>
     */
    java.lang.String getGaid();
    /**
     * <code>string gaid = 5;</code>
     */
    com.google.protobuf.ByteString
        getGaidBytes();

    /**
     * <code>string platform = 6;</code>
     */
    java.lang.String getPlatform();
    /**
     * <code>string platform = 6;</code>
     */
    com.google.protobuf.ByteString
        getPlatformBytes();

    /**
     * <code>string country = 7;</code>
     */
    java.lang.String getCountry();
    /**
     * <code>string country = 7;</code>
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    /**
     * <code>string appVer = 8;</code>
     */
    java.lang.String getAppVer();
    /**
     * <code>string appVer = 8;</code>
     */
    com.google.protobuf.ByteString
        getAppVerBytes();

    /**
     * <code>int32 protoVer = 9;</code>
     */
    int getProtoVer();

    /**
     * <code>bool isQuiet = 10;</code>
     */
    boolean getIsQuiet();
  }
  /**
   * Protobuf type {@code CSLogin}
   */
  public  static final class CSLogin extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CSLogin)
      CSLoginOrBuilder {
    // Use CSLogin.newBuilder() to construct.
    private CSLogin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CSLogin() {
      deviceId_ = "";
      userId_ = "";
      zoneName_ = "";
      account_ = "";
      gaid_ = "";
      platform_ = "";
      country_ = "";
      appVer_ = "";
      protoVer_ = 0;
      isQuiet_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CSLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              zoneName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              account_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              gaid_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              platform_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              country_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              appVer_ = s;
              break;
            }
            case 72: {

              protoVer_ = input.readInt32();
              break;
            }
            case 80: {

              isQuiet_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dd.protobuf.LoginProtocol.internal_static_CSLogin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dd.protobuf.LoginProtocol.internal_static_CSLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dd.protobuf.LoginProtocol.CSLogin.class, com.dd.protobuf.LoginProtocol.CSLogin.Builder.class);
    }

    public static final int DEVICEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object deviceId_;
    /**
     * <code>string DeviceId = 1;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <code>string DeviceId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private volatile java.lang.Object userId_;
    /**
     * <code>string UserId = 2;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string UserId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ZONENAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object zoneName_;
    /**
     * <code>string zoneName = 3;</code>
     */
    public java.lang.String getZoneName() {
      java.lang.Object ref = zoneName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        zoneName_ = s;
        return s;
      }
    }
    /**
     * <code>string zoneName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getZoneNameBytes() {
      java.lang.Object ref = zoneName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zoneName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNT_FIELD_NUMBER = 4;
    private volatile java.lang.Object account_;
    /**
     * <code>string account = 4;</code>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        account_ = s;
        return s;
      }
    }
    /**
     * <code>string account = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GAID_FIELD_NUMBER = 5;
    private volatile java.lang.Object gaid_;
    /**
     * <code>string gaid = 5;</code>
     */
    public java.lang.String getGaid() {
      java.lang.Object ref = gaid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gaid_ = s;
        return s;
      }
    }
    /**
     * <code>string gaid = 5;</code>
     */
    public com.google.protobuf.ByteString
        getGaidBytes() {
      java.lang.Object ref = gaid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gaid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLATFORM_FIELD_NUMBER = 6;
    private volatile java.lang.Object platform_;
    /**
     * <code>string platform = 6;</code>
     */
    public java.lang.String getPlatform() {
      java.lang.Object ref = platform_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        platform_ = s;
        return s;
      }
    }
    /**
     * <code>string platform = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      java.lang.Object ref = platform_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRY_FIELD_NUMBER = 7;
    private volatile java.lang.Object country_;
    /**
     * <code>string country = 7;</code>
     */
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        country_ = s;
        return s;
      }
    }
    /**
     * <code>string country = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPVER_FIELD_NUMBER = 8;
    private volatile java.lang.Object appVer_;
    /**
     * <code>string appVer = 8;</code>
     */
    public java.lang.String getAppVer() {
      java.lang.Object ref = appVer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appVer_ = s;
        return s;
      }
    }
    /**
     * <code>string appVer = 8;</code>
     */
    public com.google.protobuf.ByteString
        getAppVerBytes() {
      java.lang.Object ref = appVer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appVer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROTOVER_FIELD_NUMBER = 9;
    private int protoVer_;
    /**
     * <code>int32 protoVer = 9;</code>
     */
    public int getProtoVer() {
      return protoVer_;
    }

    public static final int ISQUIET_FIELD_NUMBER = 10;
    private boolean isQuiet_;
    /**
     * <code>bool isQuiet = 10;</code>
     */
    public boolean getIsQuiet() {
      return isQuiet_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceId_);
      }
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userId_);
      }
      if (!getZoneNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, zoneName_);
      }
      if (!getAccountBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, account_);
      }
      if (!getGaidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, gaid_);
      }
      if (!getPlatformBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, platform_);
      }
      if (!getCountryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, country_);
      }
      if (!getAppVerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, appVer_);
      }
      if (protoVer_ != 0) {
        output.writeInt32(9, protoVer_);
      }
      if (isQuiet_ != false) {
        output.writeBool(10, isQuiet_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceId_);
      }
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userId_);
      }
      if (!getZoneNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, zoneName_);
      }
      if (!getAccountBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, account_);
      }
      if (!getGaidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, gaid_);
      }
      if (!getPlatformBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, platform_);
      }
      if (!getCountryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, country_);
      }
      if (!getAppVerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, appVer_);
      }
      if (protoVer_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, protoVer_);
      }
      if (isQuiet_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, isQuiet_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dd.protobuf.LoginProtocol.CSLogin)) {
        return super.equals(obj);
      }
      com.dd.protobuf.LoginProtocol.CSLogin other = (com.dd.protobuf.LoginProtocol.CSLogin) obj;

      boolean result = true;
      result = result && getDeviceId()
          .equals(other.getDeviceId());
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && getZoneName()
          .equals(other.getZoneName());
      result = result && getAccount()
          .equals(other.getAccount());
      result = result && getGaid()
          .equals(other.getGaid());
      result = result && getPlatform()
          .equals(other.getPlatform());
      result = result && getCountry()
          .equals(other.getCountry());
      result = result && getAppVer()
          .equals(other.getAppVer());
      result = result && (getProtoVer()
          == other.getProtoVer());
      result = result && (getIsQuiet()
          == other.getIsQuiet());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + ZONENAME_FIELD_NUMBER;
      hash = (53 * hash) + getZoneName().hashCode();
      hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAccount().hashCode();
      hash = (37 * hash) + GAID_FIELD_NUMBER;
      hash = (53 * hash) + getGaid().hashCode();
      hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
      hash = (53 * hash) + getPlatform().hashCode();
      hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + getCountry().hashCode();
      hash = (37 * hash) + APPVER_FIELD_NUMBER;
      hash = (53 * hash) + getAppVer().hashCode();
      hash = (37 * hash) + PROTOVER_FIELD_NUMBER;
      hash = (53 * hash) + getProtoVer();
      hash = (37 * hash) + ISQUIET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsQuiet());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dd.protobuf.LoginProtocol.CSLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dd.protobuf.LoginProtocol.CSLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dd.protobuf.LoginProtocol.CSLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dd.protobuf.LoginProtocol.CSLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dd.protobuf.LoginProtocol.CSLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.LoginProtocol.CSLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dd.protobuf.LoginProtocol.CSLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.LoginProtocol.CSLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dd.protobuf.LoginProtocol.CSLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.LoginProtocol.CSLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dd.protobuf.LoginProtocol.CSLogin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CSLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CSLogin)
        com.dd.protobuf.LoginProtocol.CSLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dd.protobuf.LoginProtocol.internal_static_CSLogin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dd.protobuf.LoginProtocol.internal_static_CSLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dd.protobuf.LoginProtocol.CSLogin.class, com.dd.protobuf.LoginProtocol.CSLogin.Builder.class);
      }

      // Construct using com.dd.protobuf.LoginProtocol.CSLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        deviceId_ = "";

        userId_ = "";

        zoneName_ = "";

        account_ = "";

        gaid_ = "";

        platform_ = "";

        country_ = "";

        appVer_ = "";

        protoVer_ = 0;

        isQuiet_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dd.protobuf.LoginProtocol.internal_static_CSLogin_descriptor;
      }

      public com.dd.protobuf.LoginProtocol.CSLogin getDefaultInstanceForType() {
        return com.dd.protobuf.LoginProtocol.CSLogin.getDefaultInstance();
      }

      public com.dd.protobuf.LoginProtocol.CSLogin build() {
        com.dd.protobuf.LoginProtocol.CSLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dd.protobuf.LoginProtocol.CSLogin buildPartial() {
        com.dd.protobuf.LoginProtocol.CSLogin result = new com.dd.protobuf.LoginProtocol.CSLogin(this);
        result.deviceId_ = deviceId_;
        result.userId_ = userId_;
        result.zoneName_ = zoneName_;
        result.account_ = account_;
        result.gaid_ = gaid_;
        result.platform_ = platform_;
        result.country_ = country_;
        result.appVer_ = appVer_;
        result.protoVer_ = protoVer_;
        result.isQuiet_ = isQuiet_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dd.protobuf.LoginProtocol.CSLogin) {
          return mergeFrom((com.dd.protobuf.LoginProtocol.CSLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dd.protobuf.LoginProtocol.CSLogin other) {
        if (other == com.dd.protobuf.LoginProtocol.CSLogin.getDefaultInstance()) return this;
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getZoneName().isEmpty()) {
          zoneName_ = other.zoneName_;
          onChanged();
        }
        if (!other.getAccount().isEmpty()) {
          account_ = other.account_;
          onChanged();
        }
        if (!other.getGaid().isEmpty()) {
          gaid_ = other.gaid_;
          onChanged();
        }
        if (!other.getPlatform().isEmpty()) {
          platform_ = other.platform_;
          onChanged();
        }
        if (!other.getCountry().isEmpty()) {
          country_ = other.country_;
          onChanged();
        }
        if (!other.getAppVer().isEmpty()) {
          appVer_ = other.appVer_;
          onChanged();
        }
        if (other.getProtoVer() != 0) {
          setProtoVer(other.getProtoVer());
        }
        if (other.getIsQuiet() != false) {
          setIsQuiet(other.getIsQuiet());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dd.protobuf.LoginProtocol.CSLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dd.protobuf.LoginProtocol.CSLogin) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object deviceId_ = "";
      /**
       * <code>string DeviceId = 1;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string DeviceId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string DeviceId = 1;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string DeviceId = 1;</code>
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>string DeviceId = 1;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>string UserId = 2;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string UserId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string UserId = 2;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string UserId = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string UserId = 2;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object zoneName_ = "";
      /**
       * <code>string zoneName = 3;</code>
       */
      public java.lang.String getZoneName() {
        java.lang.Object ref = zoneName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          zoneName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string zoneName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getZoneNameBytes() {
        java.lang.Object ref = zoneName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          zoneName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string zoneName = 3;</code>
       */
      public Builder setZoneName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        zoneName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string zoneName = 3;</code>
       */
      public Builder clearZoneName() {
        
        zoneName_ = getDefaultInstance().getZoneName();
        onChanged();
        return this;
      }
      /**
       * <code>string zoneName = 3;</code>
       */
      public Builder setZoneNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        zoneName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object account_ = "";
      /**
       * <code>string account = 4;</code>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string account = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string account = 4;</code>
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string account = 4;</code>
       */
      public Builder clearAccount() {
        
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>string account = 4;</code>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        account_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gaid_ = "";
      /**
       * <code>string gaid = 5;</code>
       */
      public java.lang.String getGaid() {
        java.lang.Object ref = gaid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gaid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string gaid = 5;</code>
       */
      public com.google.protobuf.ByteString
          getGaidBytes() {
        java.lang.Object ref = gaid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gaid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gaid = 5;</code>
       */
      public Builder setGaid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gaid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string gaid = 5;</code>
       */
      public Builder clearGaid() {
        
        gaid_ = getDefaultInstance().getGaid();
        onChanged();
        return this;
      }
      /**
       * <code>string gaid = 5;</code>
       */
      public Builder setGaidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gaid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object platform_ = "";
      /**
       * <code>string platform = 6;</code>
       */
      public java.lang.String getPlatform() {
        java.lang.Object ref = platform_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          platform_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string platform = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPlatformBytes() {
        java.lang.Object ref = platform_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          platform_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string platform = 6;</code>
       */
      public Builder setPlatform(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        platform_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string platform = 6;</code>
       */
      public Builder clearPlatform() {
        
        platform_ = getDefaultInstance().getPlatform();
        onChanged();
        return this;
      }
      /**
       * <code>string platform = 6;</code>
       */
      public Builder setPlatformBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        platform_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object country_ = "";
      /**
       * <code>string country = 7;</code>
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          country_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string country = 7;</code>
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string country = 7;</code>
       */
      public Builder setCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string country = 7;</code>
       */
      public Builder clearCountry() {
        
        country_ = getDefaultInstance().getCountry();
        onChanged();
        return this;
      }
      /**
       * <code>string country = 7;</code>
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        country_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appVer_ = "";
      /**
       * <code>string appVer = 8;</code>
       */
      public java.lang.String getAppVer() {
        java.lang.Object ref = appVer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appVer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string appVer = 8;</code>
       */
      public com.google.protobuf.ByteString
          getAppVerBytes() {
        java.lang.Object ref = appVer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appVer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appVer = 8;</code>
       */
      public Builder setAppVer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appVer = 8;</code>
       */
      public Builder clearAppVer() {
        
        appVer_ = getDefaultInstance().getAppVer();
        onChanged();
        return this;
      }
      /**
       * <code>string appVer = 8;</code>
       */
      public Builder setAppVerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appVer_ = value;
        onChanged();
        return this;
      }

      private int protoVer_ ;
      /**
       * <code>int32 protoVer = 9;</code>
       */
      public int getProtoVer() {
        return protoVer_;
      }
      /**
       * <code>int32 protoVer = 9;</code>
       */
      public Builder setProtoVer(int value) {
        
        protoVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 protoVer = 9;</code>
       */
      public Builder clearProtoVer() {
        
        protoVer_ = 0;
        onChanged();
        return this;
      }

      private boolean isQuiet_ ;
      /**
       * <code>bool isQuiet = 10;</code>
       */
      public boolean getIsQuiet() {
        return isQuiet_;
      }
      /**
       * <code>bool isQuiet = 10;</code>
       */
      public Builder setIsQuiet(boolean value) {
        
        isQuiet_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isQuiet = 10;</code>
       */
      public Builder clearIsQuiet() {
        
        isQuiet_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:CSLogin)
    }

    // @@protoc_insertion_point(class_scope:CSLogin)
    private static final com.dd.protobuf.LoginProtocol.CSLogin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dd.protobuf.LoginProtocol.CSLogin();
    }

    public static com.dd.protobuf.LoginProtocol.CSLogin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CSLogin>
        PARSER = new com.google.protobuf.AbstractParser<CSLogin>() {
      public CSLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CSLogin(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CSLogin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CSLogin> getParserForType() {
      return PARSER;
    }

    public com.dd.protobuf.LoginProtocol.CSLogin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SCLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SCLogin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.PBPlayerInfo PlayerInfo = 1;</code>
     */
    boolean hasPlayerInfo();
    /**
     * <code>.PBPlayerInfo PlayerInfo = 1;</code>
     */
    com.dd.protobuf.PBStructProtocol.PBPlayerInfo getPlayerInfo();
    /**
     * <code>.PBPlayerInfo PlayerInfo = 1;</code>
     */
    com.dd.protobuf.PBStructProtocol.PBPlayerInfoOrBuilder getPlayerInfoOrBuilder();

    /**
     * <code>string functions = 2;</code>
     */
    java.lang.String getFunctions();
    /**
     * <code>string functions = 2;</code>
     */
    com.google.protobuf.ByteString
        getFunctionsBytes();

    /**
     * <code>string serverTime = 3;</code>
     */
    java.lang.String getServerTime();
    /**
     * <code>string serverTime = 3;</code>
     */
    com.google.protobuf.ByteString
        getServerTimeBytes();

    /**
     * <code>bool isRegister = 4;</code>
     */
    boolean getIsRegister();

    /**
     * <code>bool inFighting = 5;</code>
     */
    boolean getInFighting();

    /**
     * <code>int32 sessionId = 6;</code>
     */
    int getSessionId();

    /**
     * <code>string udpIp = 7;</code>
     */
    java.lang.String getUdpIp();
    /**
     * <code>string udpIp = 7;</code>
     */
    com.google.protobuf.ByteString
        getUdpIpBytes();

    /**
     * <code>int32 udpPort = 8;</code>
     */
    int getUdpPort();
  }
  /**
   * Protobuf type {@code SCLogin}
   */
  public  static final class SCLogin extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SCLogin)
      SCLoginOrBuilder {
    // Use SCLogin.newBuilder() to construct.
    private SCLogin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SCLogin() {
      functions_ = "";
      serverTime_ = "";
      isRegister_ = false;
      inFighting_ = false;
      sessionId_ = 0;
      udpIp_ = "";
      udpPort_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SCLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.dd.protobuf.PBStructProtocol.PBPlayerInfo.Builder subBuilder = null;
              if (playerInfo_ != null) {
                subBuilder = playerInfo_.toBuilder();
              }
              playerInfo_ = input.readMessage(com.dd.protobuf.PBStructProtocol.PBPlayerInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(playerInfo_);
                playerInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              functions_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              serverTime_ = s;
              break;
            }
            case 32: {

              isRegister_ = input.readBool();
              break;
            }
            case 40: {

              inFighting_ = input.readBool();
              break;
            }
            case 48: {

              sessionId_ = input.readInt32();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              udpIp_ = s;
              break;
            }
            case 64: {

              udpPort_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dd.protobuf.LoginProtocol.internal_static_SCLogin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dd.protobuf.LoginProtocol.internal_static_SCLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dd.protobuf.LoginProtocol.SCLogin.class, com.dd.protobuf.LoginProtocol.SCLogin.Builder.class);
    }

    public static final int PLAYERINFO_FIELD_NUMBER = 1;
    private com.dd.protobuf.PBStructProtocol.PBPlayerInfo playerInfo_;
    /**
     * <code>.PBPlayerInfo PlayerInfo = 1;</code>
     */
    public boolean hasPlayerInfo() {
      return playerInfo_ != null;
    }
    /**
     * <code>.PBPlayerInfo PlayerInfo = 1;</code>
     */
    public com.dd.protobuf.PBStructProtocol.PBPlayerInfo getPlayerInfo() {
      return playerInfo_ == null ? com.dd.protobuf.PBStructProtocol.PBPlayerInfo.getDefaultInstance() : playerInfo_;
    }
    /**
     * <code>.PBPlayerInfo PlayerInfo = 1;</code>
     */
    public com.dd.protobuf.PBStructProtocol.PBPlayerInfoOrBuilder getPlayerInfoOrBuilder() {
      return getPlayerInfo();
    }

    public static final int FUNCTIONS_FIELD_NUMBER = 2;
    private volatile java.lang.Object functions_;
    /**
     * <code>string functions = 2;</code>
     */
    public java.lang.String getFunctions() {
      java.lang.Object ref = functions_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        functions_ = s;
        return s;
      }
    }
    /**
     * <code>string functions = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFunctionsBytes() {
      java.lang.Object ref = functions_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        functions_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERTIME_FIELD_NUMBER = 3;
    private volatile java.lang.Object serverTime_;
    /**
     * <code>string serverTime = 3;</code>
     */
    public java.lang.String getServerTime() {
      java.lang.Object ref = serverTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverTime_ = s;
        return s;
      }
    }
    /**
     * <code>string serverTime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServerTimeBytes() {
      java.lang.Object ref = serverTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISREGISTER_FIELD_NUMBER = 4;
    private boolean isRegister_;
    /**
     * <code>bool isRegister = 4;</code>
     */
    public boolean getIsRegister() {
      return isRegister_;
    }

    public static final int INFIGHTING_FIELD_NUMBER = 5;
    private boolean inFighting_;
    /**
     * <code>bool inFighting = 5;</code>
     */
    public boolean getInFighting() {
      return inFighting_;
    }

    public static final int SESSIONID_FIELD_NUMBER = 6;
    private int sessionId_;
    /**
     * <code>int32 sessionId = 6;</code>
     */
    public int getSessionId() {
      return sessionId_;
    }

    public static final int UDPIP_FIELD_NUMBER = 7;
    private volatile java.lang.Object udpIp_;
    /**
     * <code>string udpIp = 7;</code>
     */
    public java.lang.String getUdpIp() {
      java.lang.Object ref = udpIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        udpIp_ = s;
        return s;
      }
    }
    /**
     * <code>string udpIp = 7;</code>
     */
    public com.google.protobuf.ByteString
        getUdpIpBytes() {
      java.lang.Object ref = udpIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        udpIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UDPPORT_FIELD_NUMBER = 8;
    private int udpPort_;
    /**
     * <code>int32 udpPort = 8;</code>
     */
    public int getUdpPort() {
      return udpPort_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (playerInfo_ != null) {
        output.writeMessage(1, getPlayerInfo());
      }
      if (!getFunctionsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, functions_);
      }
      if (!getServerTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, serverTime_);
      }
      if (isRegister_ != false) {
        output.writeBool(4, isRegister_);
      }
      if (inFighting_ != false) {
        output.writeBool(5, inFighting_);
      }
      if (sessionId_ != 0) {
        output.writeInt32(6, sessionId_);
      }
      if (!getUdpIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, udpIp_);
      }
      if (udpPort_ != 0) {
        output.writeInt32(8, udpPort_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (playerInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPlayerInfo());
      }
      if (!getFunctionsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, functions_);
      }
      if (!getServerTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, serverTime_);
      }
      if (isRegister_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isRegister_);
      }
      if (inFighting_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, inFighting_);
      }
      if (sessionId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, sessionId_);
      }
      if (!getUdpIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, udpIp_);
      }
      if (udpPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, udpPort_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dd.protobuf.LoginProtocol.SCLogin)) {
        return super.equals(obj);
      }
      com.dd.protobuf.LoginProtocol.SCLogin other = (com.dd.protobuf.LoginProtocol.SCLogin) obj;

      boolean result = true;
      result = result && (hasPlayerInfo() == other.hasPlayerInfo());
      if (hasPlayerInfo()) {
        result = result && getPlayerInfo()
            .equals(other.getPlayerInfo());
      }
      result = result && getFunctions()
          .equals(other.getFunctions());
      result = result && getServerTime()
          .equals(other.getServerTime());
      result = result && (getIsRegister()
          == other.getIsRegister());
      result = result && (getInFighting()
          == other.getInFighting());
      result = result && (getSessionId()
          == other.getSessionId());
      result = result && getUdpIp()
          .equals(other.getUdpIp());
      result = result && (getUdpPort()
          == other.getUdpPort());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPlayerInfo()) {
        hash = (37 * hash) + PLAYERINFO_FIELD_NUMBER;
        hash = (53 * hash) + getPlayerInfo().hashCode();
      }
      hash = (37 * hash) + FUNCTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getFunctions().hashCode();
      hash = (37 * hash) + SERVERTIME_FIELD_NUMBER;
      hash = (53 * hash) + getServerTime().hashCode();
      hash = (37 * hash) + ISREGISTER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsRegister());
      hash = (37 * hash) + INFIGHTING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getInFighting());
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId();
      hash = (37 * hash) + UDPIP_FIELD_NUMBER;
      hash = (53 * hash) + getUdpIp().hashCode();
      hash = (37 * hash) + UDPPORT_FIELD_NUMBER;
      hash = (53 * hash) + getUdpPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dd.protobuf.LoginProtocol.SCLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dd.protobuf.LoginProtocol.SCLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dd.protobuf.LoginProtocol.SCLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dd.protobuf.LoginProtocol.SCLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dd.protobuf.LoginProtocol.SCLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.LoginProtocol.SCLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dd.protobuf.LoginProtocol.SCLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.LoginProtocol.SCLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dd.protobuf.LoginProtocol.SCLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.LoginProtocol.SCLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dd.protobuf.LoginProtocol.SCLogin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SCLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SCLogin)
        com.dd.protobuf.LoginProtocol.SCLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dd.protobuf.LoginProtocol.internal_static_SCLogin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dd.protobuf.LoginProtocol.internal_static_SCLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dd.protobuf.LoginProtocol.SCLogin.class, com.dd.protobuf.LoginProtocol.SCLogin.Builder.class);
      }

      // Construct using com.dd.protobuf.LoginProtocol.SCLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (playerInfoBuilder_ == null) {
          playerInfo_ = null;
        } else {
          playerInfo_ = null;
          playerInfoBuilder_ = null;
        }
        functions_ = "";

        serverTime_ = "";

        isRegister_ = false;

        inFighting_ = false;

        sessionId_ = 0;

        udpIp_ = "";

        udpPort_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dd.protobuf.LoginProtocol.internal_static_SCLogin_descriptor;
      }

      public com.dd.protobuf.LoginProtocol.SCLogin getDefaultInstanceForType() {
        return com.dd.protobuf.LoginProtocol.SCLogin.getDefaultInstance();
      }

      public com.dd.protobuf.LoginProtocol.SCLogin build() {
        com.dd.protobuf.LoginProtocol.SCLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dd.protobuf.LoginProtocol.SCLogin buildPartial() {
        com.dd.protobuf.LoginProtocol.SCLogin result = new com.dd.protobuf.LoginProtocol.SCLogin(this);
        if (playerInfoBuilder_ == null) {
          result.playerInfo_ = playerInfo_;
        } else {
          result.playerInfo_ = playerInfoBuilder_.build();
        }
        result.functions_ = functions_;
        result.serverTime_ = serverTime_;
        result.isRegister_ = isRegister_;
        result.inFighting_ = inFighting_;
        result.sessionId_ = sessionId_;
        result.udpIp_ = udpIp_;
        result.udpPort_ = udpPort_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dd.protobuf.LoginProtocol.SCLogin) {
          return mergeFrom((com.dd.protobuf.LoginProtocol.SCLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dd.protobuf.LoginProtocol.SCLogin other) {
        if (other == com.dd.protobuf.LoginProtocol.SCLogin.getDefaultInstance()) return this;
        if (other.hasPlayerInfo()) {
          mergePlayerInfo(other.getPlayerInfo());
        }
        if (!other.getFunctions().isEmpty()) {
          functions_ = other.functions_;
          onChanged();
        }
        if (!other.getServerTime().isEmpty()) {
          serverTime_ = other.serverTime_;
          onChanged();
        }
        if (other.getIsRegister() != false) {
          setIsRegister(other.getIsRegister());
        }
        if (other.getInFighting() != false) {
          setInFighting(other.getInFighting());
        }
        if (other.getSessionId() != 0) {
          setSessionId(other.getSessionId());
        }
        if (!other.getUdpIp().isEmpty()) {
          udpIp_ = other.udpIp_;
          onChanged();
        }
        if (other.getUdpPort() != 0) {
          setUdpPort(other.getUdpPort());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dd.protobuf.LoginProtocol.SCLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dd.protobuf.LoginProtocol.SCLogin) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.dd.protobuf.PBStructProtocol.PBPlayerInfo playerInfo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dd.protobuf.PBStructProtocol.PBPlayerInfo, com.dd.protobuf.PBStructProtocol.PBPlayerInfo.Builder, com.dd.protobuf.PBStructProtocol.PBPlayerInfoOrBuilder> playerInfoBuilder_;
      /**
       * <code>.PBPlayerInfo PlayerInfo = 1;</code>
       */
      public boolean hasPlayerInfo() {
        return playerInfoBuilder_ != null || playerInfo_ != null;
      }
      /**
       * <code>.PBPlayerInfo PlayerInfo = 1;</code>
       */
      public com.dd.protobuf.PBStructProtocol.PBPlayerInfo getPlayerInfo() {
        if (playerInfoBuilder_ == null) {
          return playerInfo_ == null ? com.dd.protobuf.PBStructProtocol.PBPlayerInfo.getDefaultInstance() : playerInfo_;
        } else {
          return playerInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.PBPlayerInfo PlayerInfo = 1;</code>
       */
      public Builder setPlayerInfo(com.dd.protobuf.PBStructProtocol.PBPlayerInfo value) {
        if (playerInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          playerInfo_ = value;
          onChanged();
        } else {
          playerInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.PBPlayerInfo PlayerInfo = 1;</code>
       */
      public Builder setPlayerInfo(
          com.dd.protobuf.PBStructProtocol.PBPlayerInfo.Builder builderForValue) {
        if (playerInfoBuilder_ == null) {
          playerInfo_ = builderForValue.build();
          onChanged();
        } else {
          playerInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.PBPlayerInfo PlayerInfo = 1;</code>
       */
      public Builder mergePlayerInfo(com.dd.protobuf.PBStructProtocol.PBPlayerInfo value) {
        if (playerInfoBuilder_ == null) {
          if (playerInfo_ != null) {
            playerInfo_ =
              com.dd.protobuf.PBStructProtocol.PBPlayerInfo.newBuilder(playerInfo_).mergeFrom(value).buildPartial();
          } else {
            playerInfo_ = value;
          }
          onChanged();
        } else {
          playerInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.PBPlayerInfo PlayerInfo = 1;</code>
       */
      public Builder clearPlayerInfo() {
        if (playerInfoBuilder_ == null) {
          playerInfo_ = null;
          onChanged();
        } else {
          playerInfo_ = null;
          playerInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.PBPlayerInfo PlayerInfo = 1;</code>
       */
      public com.dd.protobuf.PBStructProtocol.PBPlayerInfo.Builder getPlayerInfoBuilder() {
        
        onChanged();
        return getPlayerInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.PBPlayerInfo PlayerInfo = 1;</code>
       */
      public com.dd.protobuf.PBStructProtocol.PBPlayerInfoOrBuilder getPlayerInfoOrBuilder() {
        if (playerInfoBuilder_ != null) {
          return playerInfoBuilder_.getMessageOrBuilder();
        } else {
          return playerInfo_ == null ?
              com.dd.protobuf.PBStructProtocol.PBPlayerInfo.getDefaultInstance() : playerInfo_;
        }
      }
      /**
       * <code>.PBPlayerInfo PlayerInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dd.protobuf.PBStructProtocol.PBPlayerInfo, com.dd.protobuf.PBStructProtocol.PBPlayerInfo.Builder, com.dd.protobuf.PBStructProtocol.PBPlayerInfoOrBuilder> 
          getPlayerInfoFieldBuilder() {
        if (playerInfoBuilder_ == null) {
          playerInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.dd.protobuf.PBStructProtocol.PBPlayerInfo, com.dd.protobuf.PBStructProtocol.PBPlayerInfo.Builder, com.dd.protobuf.PBStructProtocol.PBPlayerInfoOrBuilder>(
                  getPlayerInfo(),
                  getParentForChildren(),
                  isClean());
          playerInfo_ = null;
        }
        return playerInfoBuilder_;
      }

      private java.lang.Object functions_ = "";
      /**
       * <code>string functions = 2;</code>
       */
      public java.lang.String getFunctions() {
        java.lang.Object ref = functions_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          functions_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string functions = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFunctionsBytes() {
        java.lang.Object ref = functions_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          functions_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string functions = 2;</code>
       */
      public Builder setFunctions(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        functions_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string functions = 2;</code>
       */
      public Builder clearFunctions() {
        
        functions_ = getDefaultInstance().getFunctions();
        onChanged();
        return this;
      }
      /**
       * <code>string functions = 2;</code>
       */
      public Builder setFunctionsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        functions_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object serverTime_ = "";
      /**
       * <code>string serverTime = 3;</code>
       */
      public java.lang.String getServerTime() {
        java.lang.Object ref = serverTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serverTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string serverTime = 3;</code>
       */
      public com.google.protobuf.ByteString
          getServerTimeBytes() {
        java.lang.Object ref = serverTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serverTime = 3;</code>
       */
      public Builder setServerTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string serverTime = 3;</code>
       */
      public Builder clearServerTime() {
        
        serverTime_ = getDefaultInstance().getServerTime();
        onChanged();
        return this;
      }
      /**
       * <code>string serverTime = 3;</code>
       */
      public Builder setServerTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverTime_ = value;
        onChanged();
        return this;
      }

      private boolean isRegister_ ;
      /**
       * <code>bool isRegister = 4;</code>
       */
      public boolean getIsRegister() {
        return isRegister_;
      }
      /**
       * <code>bool isRegister = 4;</code>
       */
      public Builder setIsRegister(boolean value) {
        
        isRegister_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isRegister = 4;</code>
       */
      public Builder clearIsRegister() {
        
        isRegister_ = false;
        onChanged();
        return this;
      }

      private boolean inFighting_ ;
      /**
       * <code>bool inFighting = 5;</code>
       */
      public boolean getInFighting() {
        return inFighting_;
      }
      /**
       * <code>bool inFighting = 5;</code>
       */
      public Builder setInFighting(boolean value) {
        
        inFighting_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool inFighting = 5;</code>
       */
      public Builder clearInFighting() {
        
        inFighting_ = false;
        onChanged();
        return this;
      }

      private int sessionId_ ;
      /**
       * <code>int32 sessionId = 6;</code>
       */
      public int getSessionId() {
        return sessionId_;
      }
      /**
       * <code>int32 sessionId = 6;</code>
       */
      public Builder setSessionId(int value) {
        
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sessionId = 6;</code>
       */
      public Builder clearSessionId() {
        
        sessionId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object udpIp_ = "";
      /**
       * <code>string udpIp = 7;</code>
       */
      public java.lang.String getUdpIp() {
        java.lang.Object ref = udpIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          udpIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string udpIp = 7;</code>
       */
      public com.google.protobuf.ByteString
          getUdpIpBytes() {
        java.lang.Object ref = udpIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          udpIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string udpIp = 7;</code>
       */
      public Builder setUdpIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        udpIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string udpIp = 7;</code>
       */
      public Builder clearUdpIp() {
        
        udpIp_ = getDefaultInstance().getUdpIp();
        onChanged();
        return this;
      }
      /**
       * <code>string udpIp = 7;</code>
       */
      public Builder setUdpIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        udpIp_ = value;
        onChanged();
        return this;
      }

      private int udpPort_ ;
      /**
       * <code>int32 udpPort = 8;</code>
       */
      public int getUdpPort() {
        return udpPort_;
      }
      /**
       * <code>int32 udpPort = 8;</code>
       */
      public Builder setUdpPort(int value) {
        
        udpPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 udpPort = 8;</code>
       */
      public Builder clearUdpPort() {
        
        udpPort_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SCLogin)
    }

    // @@protoc_insertion_point(class_scope:SCLogin)
    private static final com.dd.protobuf.LoginProtocol.SCLogin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dd.protobuf.LoginProtocol.SCLogin();
    }

    public static com.dd.protobuf.LoginProtocol.SCLogin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SCLogin>
        PARSER = new com.google.protobuf.AbstractParser<SCLogin>() {
      public SCLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SCLogin(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SCLogin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SCLogin> getParserForType() {
      return PARSER;
    }

    public com.dd.protobuf.LoginProtocol.SCLogin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CSLogin_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CSLogin_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SCLogin_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SCLogin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Login.proto\032\016PBStruct.proto\"\262\001\n\007CSLogi" +
      "n\022\020\n\010DeviceId\030\001 \001(\t\022\016\n\006UserId\030\002 \001(\t\022\020\n\010z" +
      "oneName\030\003 \001(\t\022\017\n\007account\030\004 \001(\t\022\014\n\004gaid\030\005" +
      " \001(\t\022\020\n\010platform\030\006 \001(\t\022\017\n\007country\030\007 \001(\t\022" +
      "\016\n\006appVer\030\010 \001(\t\022\020\n\010protoVer\030\t \001(\005\022\017\n\007isQ" +
      "uiet\030\n \001(\010\"\256\001\n\007SCLogin\022!\n\nPlayerInfo\030\001 \001" +
      "(\0132\r.PBPlayerInfo\022\021\n\tfunctions\030\002 \001(\t\022\022\n\n" +
      "serverTime\030\003 \001(\t\022\022\n\nisRegister\030\004 \001(\010\022\022\n\n" +
      "inFighting\030\005 \001(\010\022\021\n\tsessionId\030\006 \001(\005\022\r\n\005u" +
      "dpIp\030\007 \001(\t\022\017\n\007udpPort\030\010 \001(\005B \n\017com.dd.pr",
      "otobufB\rLoginProtocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dd.protobuf.PBStructProtocol.getDescriptor(),
        }, assigner);
    internal_static_CSLogin_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CSLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CSLogin_descriptor,
        new java.lang.String[] { "DeviceId", "UserId", "ZoneName", "Account", "Gaid", "Platform", "Country", "AppVer", "ProtoVer", "IsQuiet", });
    internal_static_SCLogin_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SCLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SCLogin_descriptor,
        new java.lang.String[] { "PlayerInfo", "Functions", "ServerTime", "IsRegister", "InFighting", "SessionId", "UdpIp", "UdpPort", });
    com.dd.protobuf.PBStructProtocol.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
