// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Push.proto

package com.dd.protobuf;

public final class PushProtocol {
  private PushProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PushFunctionOpenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PushFunctionOpen)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string functions = 1;</code>
     */
    java.lang.String getFunctions();
    /**
     * <code>string functions = 1;</code>
     */
    com.google.protobuf.ByteString
        getFunctionsBytes();
  }
  /**
   * Protobuf type {@code PushFunctionOpen}
   */
  public  static final class PushFunctionOpen extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PushFunctionOpen)
      PushFunctionOpenOrBuilder {
    // Use PushFunctionOpen.newBuilder() to construct.
    private PushFunctionOpen(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PushFunctionOpen() {
      functions_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PushFunctionOpen(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              functions_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dd.protobuf.PushProtocol.internal_static_PushFunctionOpen_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dd.protobuf.PushProtocol.internal_static_PushFunctionOpen_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dd.protobuf.PushProtocol.PushFunctionOpen.class, com.dd.protobuf.PushProtocol.PushFunctionOpen.Builder.class);
    }

    public static final int FUNCTIONS_FIELD_NUMBER = 1;
    private volatile java.lang.Object functions_;
    /**
     * <code>string functions = 1;</code>
     */
    public java.lang.String getFunctions() {
      java.lang.Object ref = functions_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        functions_ = s;
        return s;
      }
    }
    /**
     * <code>string functions = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFunctionsBytes() {
      java.lang.Object ref = functions_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        functions_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFunctionsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, functions_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFunctionsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, functions_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dd.protobuf.PushProtocol.PushFunctionOpen)) {
        return super.equals(obj);
      }
      com.dd.protobuf.PushProtocol.PushFunctionOpen other = (com.dd.protobuf.PushProtocol.PushFunctionOpen) obj;

      boolean result = true;
      result = result && getFunctions()
          .equals(other.getFunctions());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FUNCTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getFunctions().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dd.protobuf.PushProtocol.PushFunctionOpen parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dd.protobuf.PushProtocol.PushFunctionOpen parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dd.protobuf.PushProtocol.PushFunctionOpen parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dd.protobuf.PushProtocol.PushFunctionOpen parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dd.protobuf.PushProtocol.PushFunctionOpen parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.PushProtocol.PushFunctionOpen parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dd.protobuf.PushProtocol.PushFunctionOpen parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.PushProtocol.PushFunctionOpen parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dd.protobuf.PushProtocol.PushFunctionOpen parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dd.protobuf.PushProtocol.PushFunctionOpen parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dd.protobuf.PushProtocol.PushFunctionOpen prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PushFunctionOpen}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PushFunctionOpen)
        com.dd.protobuf.PushProtocol.PushFunctionOpenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dd.protobuf.PushProtocol.internal_static_PushFunctionOpen_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dd.protobuf.PushProtocol.internal_static_PushFunctionOpen_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dd.protobuf.PushProtocol.PushFunctionOpen.class, com.dd.protobuf.PushProtocol.PushFunctionOpen.Builder.class);
      }

      // Construct using com.dd.protobuf.PushProtocol.PushFunctionOpen.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        functions_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dd.protobuf.PushProtocol.internal_static_PushFunctionOpen_descriptor;
      }

      public com.dd.protobuf.PushProtocol.PushFunctionOpen getDefaultInstanceForType() {
        return com.dd.protobuf.PushProtocol.PushFunctionOpen.getDefaultInstance();
      }

      public com.dd.protobuf.PushProtocol.PushFunctionOpen build() {
        com.dd.protobuf.PushProtocol.PushFunctionOpen result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dd.protobuf.PushProtocol.PushFunctionOpen buildPartial() {
        com.dd.protobuf.PushProtocol.PushFunctionOpen result = new com.dd.protobuf.PushProtocol.PushFunctionOpen(this);
        result.functions_ = functions_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dd.protobuf.PushProtocol.PushFunctionOpen) {
          return mergeFrom((com.dd.protobuf.PushProtocol.PushFunctionOpen)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dd.protobuf.PushProtocol.PushFunctionOpen other) {
        if (other == com.dd.protobuf.PushProtocol.PushFunctionOpen.getDefaultInstance()) return this;
        if (!other.getFunctions().isEmpty()) {
          functions_ = other.functions_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dd.protobuf.PushProtocol.PushFunctionOpen parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dd.protobuf.PushProtocol.PushFunctionOpen) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object functions_ = "";
      /**
       * <code>string functions = 1;</code>
       */
      public java.lang.String getFunctions() {
        java.lang.Object ref = functions_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          functions_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string functions = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFunctionsBytes() {
        java.lang.Object ref = functions_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          functions_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string functions = 1;</code>
       */
      public Builder setFunctions(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        functions_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string functions = 1;</code>
       */
      public Builder clearFunctions() {
        
        functions_ = getDefaultInstance().getFunctions();
        onChanged();
        return this;
      }
      /**
       * <code>string functions = 1;</code>
       */
      public Builder setFunctionsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        functions_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PushFunctionOpen)
    }

    // @@protoc_insertion_point(class_scope:PushFunctionOpen)
    private static final com.dd.protobuf.PushProtocol.PushFunctionOpen DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dd.protobuf.PushProtocol.PushFunctionOpen();
    }

    public static com.dd.protobuf.PushProtocol.PushFunctionOpen getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PushFunctionOpen>
        PARSER = new com.google.protobuf.AbstractParser<PushFunctionOpen>() {
      public PushFunctionOpen parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PushFunctionOpen(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PushFunctionOpen> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PushFunctionOpen> getParserForType() {
      return PARSER;
    }

    public com.dd.protobuf.PushProtocol.PushFunctionOpen getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PushFunctionOpen_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PushFunctionOpen_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nPush.proto\"%\n\020PushFunctionOpen\022\021\n\tfunc" +
      "tions\030\001 \001(\tB\037\n\017com.dd.protobufB\014PushProt" +
      "ocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PushFunctionOpen_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PushFunctionOpen_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PushFunctionOpen_descriptor,
        new java.lang.String[] { "Functions", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
